import { type TierType } from "./benefits-config";

import iconHealthInsurance from "@/assets/icons/health-insurance.png";
import iconLifeInsurance from "@/assets/icons/life-insurance.png";
import iconFlexAllowance from "@/assets/icons/flex-allowance.png";
import iconCycleToWork from "@/assets/icons/cycle-to-work.png";
import iconLearning from "@/assets/icons/learning.png";
import iconParentalLeave from "@/assets/icons/parental-leave.png";
import iconIncomeProtection from "@/assets/icons/income-protection.png";
import iconMealAllowance from "@/assets/icons/meal-allowance.png";

export interface BenefitDetail {
  id: string;
  title: string;
  provider: string;
  category: string;
  tier: TierType;
  status: "enrolled" | "active" | "available" | "enrollment";
  icon: string;
  description: string;
  annualValue: string;
  monthlyCost: string;
  companyPays: string;
  youPay: string;
  paymentMethod: string;
  paymentFrequency: string;
  taxBenefit?: string;
  enrollmentDeadline?: string;
  included: string[];
  notCovered?: string[];
  tags: string[];
  plans?: { name: string; desc: string; cost: string; badge: string | null }[];
  // For allowance-type benefits
  allowance?: { spent: number; total: number; resets: string; creditSchedule: string };
  eligibleCategories?: string[];
  transactions?: { desc: string; date: string; amount: number }[];
}

export const benefitsData: Record<string, BenefitDetail> = {
  "health-insurance": {
    id: "health-insurance",
    title: "Private Medical Insurance",
    provider: "Bupa",
    category: "insurance",
    tier: "standard",
    status: "enrollment",
    icon: iconHealthInsurance,
    description: "Full private medical cover including inpatient treatment, outpatient consultations, mental health support, cancer care, and 24/7 GP access. Choose a plan that fits your needs.",
    annualValue: "£4,200",
    monthlyCost: "£0/mo",
    companyPays: "£4,200/yr",
    youPay: "£0/yr",
    paymentMethod: "Salary deduction",
    paymentFrequency: "Monthly",
    taxBenefit: "Pre-tax (BIK exempt)",
    enrollmentDeadline: "14 days",
    included: [
      "Inpatient & day-patient treatment",
      "Outpatient consultations & diagnostics",
      "Mental health — therapy & psychiatry",
      "Cancer treatment & care",
      "24/7 virtual GP access",
      "Optical cover",
    ],
    notCovered: ["Pre-existing conditions (2yr)", "Cosmetic procedures", "Fertility treatment"],
    tags: ["Enrollment window", "Salary sacrifice"],
    plans: [
      { name: "Individual", desc: "You only · Employer covers £4,200/yr", cost: "£0/mo", badge: "Most chosen" },
      { name: "You + Partner", desc: "You + 1 partner · Employer covers £6,800/yr", cost: "£85/mo", badge: null },
      { name: "Family", desc: "Up to 4 dependants · Employer covers £9,400/yr", cost: "£145/mo", badge: null },
    ],
  },
  "life-insurance": {
    id: "life-insurance",
    title: "Life Assurance",
    provider: "Aviva",
    category: "insurance",
    tier: "standard",
    status: "enrolled",
    icon: iconLifeInsurance,
    description: "Provides financial protection for your family with a lump sum payment of 4x your annual salary in the event of death in service, plus additional critical illness benefit.",
    annualValue: "£3,600",
    monthlyCost: "£0/mo",
    companyPays: "£3,600/yr",
    youPay: "£0/yr",
    paymentMethod: "Company funded",
    paymentFrequency: "N/A",
    included: [
      "4x annual salary death-in-service benefit",
      "Critical illness cover",
      "Terminal illness benefit",
      "Bereavement support for family",
      "Free will-writing service",
    ],
    tags: ["Active", "Company paid"],
  },
  "dental-plan": {
    id: "dental-plan",
    title: "Dental Plan",
    provider: "Denplan",
    category: "insurance",
    tier: "standard",
    status: "enrollment",
    icon: iconHealthInsurance,
    description: "Comprehensive dental coverage for routine check-ups, hygienist visits, and emergency treatment. Covers you and your family for peace of mind.",
    annualValue: "£216",
    monthlyCost: "£18/mo",
    companyPays: "£0/yr",
    youPay: "£216/yr",
    paymentMethod: "Salary deduction",
    paymentFrequency: "Monthly",
    enrollmentDeadline: "14 days",
    included: [
      "Routine check-ups (2 per year)",
      "Hygienist visits",
      "Emergency dental treatment",
      "Fillings & extractions",
      "X-rays & diagnostics",
    ],
    notCovered: ["Cosmetic dentistry", "Orthodontics (adults)", "Implants"],
    tags: ["Enrollment window"],
    plans: [
      { name: "Individual", desc: "You only", cost: "£18/mo", badge: null },
      { name: "Family", desc: "You + dependants", cost: "£35/mo", badge: null },
    ],
  },
  "income-protection": {
    id: "income-protection",
    title: "Income Protection",
    provider: "Unum",
    category: "insurance",
    tier: "standard",
    status: "enrollment",
    icon: iconIncomeProtection,
    description: "Replaces 75% of your salary if you're unable to work due to long-term illness or injury. Provides financial security when you need it most.",
    annualValue: "£144",
    monthlyCost: "£12/mo",
    companyPays: "£0/yr",
    youPay: "£144/yr",
    paymentMethod: "Salary deduction",
    paymentFrequency: "Monthly",
    included: [
      "75% salary replacement",
      "Cover from day 29 of absence",
      "Pays until return to work or retirement",
      "Rehabilitation support",
      "Employee assistance programme",
    ],
    tags: ["Enrollment open"],
  },
  "travel-insurance": {
    id: "travel-insurance",
    title: "Travel Insurance",
    provider: "AXA",
    category: "insurance",
    tier: "premium",
    status: "available",
    icon: iconLifeInsurance,
    description: "Worldwide travel insurance covering business and leisure trips for you and your family. Includes medical emergencies, cancellation, and lost luggage.",
    annualValue: "£96",
    monthlyCost: "£8/mo",
    companyPays: "£0/yr",
    youPay: "£96/yr",
    paymentMethod: "Salary deduction",
    paymentFrequency: "Monthly",
    included: [
      "Worldwide medical cover up to £10M",
      "Trip cancellation & curtailment",
      "Lost & delayed baggage",
      "Personal liability cover",
      "Winter sports cover",
      "Business travel included",
    ],
    notCovered: ["Adventure sports (without add-on)", "Pre-existing medical conditions"],
    tags: ["Quick activate"],
  },
  "wellbeing-allowance": {
    id: "wellbeing-allowance",
    title: "Wellbeing Allowance",
    provider: "Happl Spend",
    category: "allowance",
    tier: "premium",
    status: "active",
    icon: iconFlexAllowance,
    description: "Monthly budget for gym, fitness, mental health apps, wellness retreats, and sports equipment. Spend via Happl card or claim receipts.",
    annualValue: "£600",
    monthlyCost: "£0/mo",
    companyPays: "£600/yr",
    youPay: "£0/yr",
    paymentMethod: "Happl Flex Card",
    paymentFrequency: "1st of month",
    included: [
      "Gym & fitness memberships",
      "Mental health apps & therapy",
      "Sports equipment",
      "Massage & physiotherapy",
      "Wellness retreats",
    ],
    tags: ["Flex card", "Active"],
    allowance: { spent: 150, total: 600, resets: "Resets Jan 2027", creditSchedule: "£50/month · Auto-credited on 1st" },
    eligibleCategories: ["Gym & fitness", "Mental health", "Sports equipment", "Massage & physio", "Wellness retreats"],
    transactions: [
      { desc: "PureGym", date: "28 Mar", amount: -29.99 },
      { desc: "Headspace", date: "15 Mar", amount: -9.99 },
      { desc: "Sweaty Betty", date: "2 Mar", amount: -65.00 },
      { desc: "Barry's Bootcamp", date: "18 Feb", amount: -24.00 },
    ],
  },
  "learning-budget": {
    id: "learning-budget",
    title: "Learning & Development",
    provider: "Happl Spend",
    category: "allowance",
    tier: "premium",
    status: "active",
    icon: iconLearning,
    description: "Annual budget for courses, conferences, books, and professional development. Invest in your growth with employer-funded learning.",
    annualValue: "£1,000",
    monthlyCost: "£0/mo",
    companyPays: "£1,000/yr",
    youPay: "£0/yr",
    paymentMethod: "Happl Flex Card",
    paymentFrequency: "Annual credit",
    included: [
      "Online courses & certifications",
      "Conference & event tickets",
      "Books & subscriptions",
      "Professional memberships",
      "Training workshops",
    ],
    tags: ["Flex card", "Active"],
    allowance: { spent: 200, total: 1000, resets: "Resets Jan 2027", creditSchedule: "£1,000/year · Credited annually" },
    eligibleCategories: ["Online courses", "Conferences", "Books", "Certifications", "Professional memberships"],
    transactions: [
      { desc: "Udemy Course", date: "10 Mar", amount: -49.99 },
      { desc: "O'Reilly Subscription", date: "1 Mar", amount: -39.00 },
      { desc: "React Summit Ticket", date: "15 Feb", amount: -99.00 },
    ],
  },
  "mental-health": {
    id: "mental-health",
    title: "Mental Health Support",
    provider: "Spill",
    category: "allowance",
    tier: "premium",
    status: "available",
    icon: iconParentalLeave,
    description: "Access 8 free therapy sessions per year with qualified therapists. Confidential support for stress, anxiety, depression, and personal challenges.",
    annualValue: "£960",
    monthlyCost: "£0/mo",
    companyPays: "£960/yr",
    youPay: "£0/yr",
    paymentMethod: "Company funded",
    paymentFrequency: "N/A",
    included: [
      "8 free therapy sessions per year",
      "Licensed & qualified therapists",
      "Video or phone sessions",
      "Completely confidential",
      "Self-referral — no manager approval",
      "Same-week appointments",
    ],
    tags: ["Quick activate", "Confidential"],
  },
  "annual-leave": {
    id: "annual-leave",
    title: "Annual Leave",
    provider: "Company",
    category: "company",
    tier: "benefits",
    status: "active",
    icon: iconMealAllowance,
    description: "25 days annual leave plus bank holidays. Option to buy or sell up to 5 additional days per year through salary adjustment.",
    annualValue: "N/A",
    monthlyCost: "£0/mo",
    companyPays: "Company benefit",
    youPay: "£0",
    paymentMethod: "N/A",
    paymentFrequency: "N/A",
    included: [
      "25 days annual leave",
      "All UK bank holidays",
      "Buy up to 5 extra days",
      "Sell up to 5 days",
      "Carry over up to 5 days",
      "Birthday day off",
    ],
    tags: ["Active", "Company benefit"],
  },
  "workplace-pension": {
    id: "workplace-pension",
    title: "Workplace Pension",
    provider: "Aviva",
    category: "pension-gov",
    tier: "benefits",
    status: "enrolled",
    icon: iconIncomeProtection,
    description: "Auto-enrolled workplace pension with employer contributing 5% and employee contributing minimum 3%. Grow your retirement savings with matched contributions.",
    annualValue: "Variable",
    monthlyCost: "3% of salary",
    companyPays: "5% of salary",
    youPay: "3% of salary",
    paymentMethod: "Salary deduction",
    paymentFrequency: "Monthly",
    taxBenefit: "Pre-tax contribution",
    included: [
      "5% employer contribution",
      "Minimum 3% employee contribution",
      "Tax relief on contributions",
      "Wide fund selection",
      "Online portal access",
      "Retirement planning tools",
    ],
    tags: ["Auto-enrolled", "Tax efficient"],
  },
  "cycle-to-work": {
    id: "cycle-to-work",
    title: "Cycle to Work",
    provider: "Cyclescheme",
    category: "pension-gov",
    tier: "govt",
    status: "available",
    icon: iconCycleToWork,
    description: "Save up to 42% on a new bike and accessories through salary sacrifice. Tax-efficient scheme to help you commute greener and healthier.",
    annualValue: "Up to £1,000",
    monthlyCost: "Salary sacrifice",
    companyPays: "£0",
    youPay: "Salary sacrifice",
    paymentMethod: "Salary sacrifice",
    paymentFrequency: "12 monthly instalments",
    taxBenefit: "Save NI & Income Tax",
    included: [
      "New bike up to £1,000",
      "Accessories & safety equipment",
      "Save up to 42% vs retail",
      "12-month salary sacrifice",
      "Keep the bike after scheme ends",
    ],
    tags: ["Tax efficient", "Green"],
  },
  "ev-scheme": {
    id: "ev-scheme",
    title: "Electric Vehicle Scheme",
    provider: "Octopus EV",
    category: "salary-sacrifice",
    tier: "sacrifice",
    status: "available",
    icon: iconCycleToWork,
    description: "Drive a brand new electric vehicle with savings of up to 40% compared to personal leasing. Includes insurance, maintenance, and breakdown cover.",
    annualValue: "Variable",
    monthlyCost: "Salary sacrifice",
    companyPays: "£0",
    youPay: "Salary sacrifice",
    paymentMethod: "Salary sacrifice",
    paymentFrequency: "Monthly",
    taxBenefit: "2% BIK rate",
    included: [
      "Brand new EV of your choice",
      "Fully comprehensive insurance",
      "Servicing & maintenance",
      "Breakdown cover",
      "Tyre replacement",
      "Save up to 40% vs personal lease",
    ],
    tags: ["Salary sacrifice", "Green"],
  },
};
